package xyz.zlatanov.frakkintoasters.card;

public enum LoyaltyCard {
    NOT_CYLON,
    NOT_CYLON_MUTINEER,
    NOT_CYLON_USE_CAUTION,
    NOT_CYLON_STAND_AND_FIGHT,
    NOT_CYLON_SELFISH,
    NOT_CYLON_SELF_DESTRUCTION,
    NOT_CYLON_SACRIFICE,
    NOT_CYLON_POLITICAL_INTRIGUE,
    NOT_CYLON_DEVASTATION,
    NOT_CYLON_ACQUIRE_POWER,
    FINAL_FIVE_YOU_ARE_SENT_TO_BRIG,
    FINAL_FIVE_YOU_ARE_EXECUTED,
    FINAL_FIVE_THEY_ARE_EXECUTED,
    FINAL_FIVE_DAMAGE_GALACTICA_TWICE,
    FINAL_FIVE_CYLON_SHIPS_ACTIVATE,
    CYLON_CAN_PLACE_CENTURION,
    CYLON_DECREASE_JUMP_TRACK,
    CYLON_DRAW_TREACHERY_CARDS,
    CYLON_SEND_TO_BRIG,
    CYLON_DAMAGE_GALACTICA,
    CYLON_REDUCE_MORALE,
    CYLON_SEND_TO_SICKBAY
}
