package xyz.zlatanov.frakkintoasters.card;

public enum MutinyCard {
    WEAPONS_ARMED,
    VIOLENT_PROTEST,
    UNAUTHORIZED_USAGE,
    THE_STRONG_SURVIVE,
    SET_THE_AGENDA,
    SEND_A_MESSAGE,
    SELFISH_ACT,
    SCAVENGING_FOR_PARTS,
    RUINED_REPUTATION,
    PEACEFUL_RESISTANCE,
    PANIC,
    NECESSARY_RISK,
    MAKE_A_DEAL,
    IMPEACHMENT,
    FEED_THE_PEOPLE,
    CONTROVERSIAL_SPEECH,
    CLIPPED_WINGS,
    BLACKMAIL,
    BETRAYAL_OF_TRUST,
    BAIT_AND_SWITCH,
    ASSUME_COMMAND,
    ARMED_RESISTANCE
}
