package xyz.zlatanov.frakkintoasters.state.skill;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.experimental.Accessors;

import static xyz.zlatanov.frakkintoasters.state.skill.SkillCardColor.*;

@Getter
@Accessors(fluent = true)
@RequiredArgsConstructor
public enum SkillCardType {
    CONSOLIDATE_POWER(POLITICS),
    INVESTIGATIVE_COMMITTEE(POLITICS),
    SUPPORT_THE_PEOPLE(POLITICS),
    PREVENTIVE_POLICY(POLITICS),
    RED_TAPE(POLITICS),
    POLITICAL_PROWESS(POLITICS),
    FORCE_THEIR_HAND(POLITICS),
    POPULAR_INFLUENCE(POLITICS),
    NEGOTIATION(POLITICS),

    EXECUTIVE_ORDER(LEADERSHIP),
    DECLARE_EMERGENCY(LEADERSHIP),
    MAJOR_VICTORY(LEADERSHIP),
    AT_ANY_COST(LEADERSHIP),
    IRON_WILL(LEADERSHIP),
    STATE_OF_EMERGENCY(LEADERSHIP),
    ALL_HANDS_ON_DECK(LEADERSHIP),
    RESTORE_ORDER(LEADERSHIP),
    CHANGE_OF_PLANS(LEADERSHIP),

    LAUNCH_SCOUT(TACTICS),
    STRATEGIC_PLANNING(TACTICS),
    GUTS_AND_INITIATIVE(TACTICS),
    CRITICAL_SITUATION(TACTICS),
    TRUST_INSTINCTS(TACTICS),
    SCOUTING_FOR_FUEL(TACTICS),
    QUICK_THINKING(TACTICS),
    UNORTHODOX_PLAN(TACTICS),
    A_SECOND_CHANCE(TACTICS),

    EVASIVE_MANOEUVRES(PILOTING),
    MAXIMUM_FIREPOWER(PILOTING),
    FULL_THROTTLE(PILOTING),
    RUN_INTERFERENCE(PILOTING),
    PROTECT_THE_FLEET(PILOTING),
    BEST_OF_THE_BEST(PILOTING),
    DOGFIGHT(PILOTING),
    COMBAT_VETERAN(PILOTING),
    LAUNCH_RESERVES(PILOTING),

    REPAIR(ENGINEERING),
    SCIENTIFIC_RESEARCH(ENGINEERING),
    JURY_RIGGED(ENGINEERING),
    CALCULATIONS(ENGINEERING),
    ESTABLISH_NETWORK(ENGINEERING),
    BUILD_NUKE(ENGINEERING),
    INSTALL_UPGRADE(ENGINEERING),
    RAPTOR_SPECIALIST(ENGINEERING),
    TEST_THE_LIMITS(ENGINEERING),

    DRAIDIS_CONTACT(TREACHERY),
    BAIT(TREACHERY),
    A_BETTER_MACHINE(TREACHERY),
    PERSONAL_VICES(TREACHERY),
    VIOLENT_OUTBURSTS(TREACHERY),
    EXPLOIT_A_WEAKNESS(TREACHERY);

    private final SkillCardColor type;
}
