package xyz.zlatanov.frakkintoasters;

public enum Location {
    //galactica
    FTL_CONTROL,
    WEAPONS_CONTROL,
    COMMUNICATIONS,
    RESEARCH_LAB,
    ARMORY,
    COMMAND,
    ADMIRALS_QUARTERS,
    HANGAR_DECK,
    SICKBAY,
    BRIG,

    //colonial one
    PRESS_ROOM,
    PRESIDENTS_OFFICE,
    ADMINISTRATION,

    //cylon
    CAPRICA,
    CYLON_FLEET,
    HUMAN_FLEET,
    RESURRECTION_SHIP,

    //galactica space
    GALACTICA_SPACE_12_OCLOCK,
    GALACTICA_SPACE_2_OCLOCK,
    GALACTICA_SPACE_4_OCLOCK,
    GALACTICA_SPACE_6_OCLOCK,
    GALACTICA_SPACE_8_OCLOCK,

    //pegasus
    PEGASUS_CIC,
    AIRLOCK,
    MAIN_BATTERIES,
    ENGINE_ROOM,

    //demetrius
    BRIDGE,
    TACTICAL_PLOT,
    CAPTAINS_CABIN,

    //cylon fleet
    BASESTAR_BRIDGE,
    CYLON_FLEET_SPACE_1,
    CYLON_FLEET_SPACE_2,
    CYLON_FLEET_SPACE_3,
    CYLON_FLEET_SPACE_4,
    CYLON_FLEET_SPACE_5_6,
    CYLON_FLEET_SPACE_7_8,

    //new caprica
    MEDICAL_CENTER,
    RESISTANCE_HQ,
    DETENTION,
    OCCUPATION_AUTHORITY,
    BREEDERS_CANYON,
    SHIPYARD
}
