package xyz.zlatanov.frakkintoasters;

public enum QuorumCard {
    ESTABLISH_DOGSVILLE,
    PRESIDENTIAL_ORDER,
    RESIGNATION,
    ACCEPT_PROPHECY,
    ARREST_ORDER,
    ASSIGN_ARBITRATOR,
    ASSIGN_MISSION_SPECIALIST,
    ASSIGN_VICE_PRESIDENT,
    AUTHORIZATION_OF_BRUTAL_FORCE,
    ENCOURAGE_MUTINY,
    FOOD_RATIONING,
    INSPIRATIONAL_SPEECH,
    PRESIDENTIAL_PARDON,
    RELEASE_CYLON_MUGSHOTS,
    ASSIGN_CHIEF_OF_STAFF,
    CIVILIAN_SELF_DEFENSE,
    CONSULT_THE_ORACLE,
    ENACT_PRODUCTION_QUOTAS,
    EULOGY,
    EXECUTE_PRISONER,
    PROBATION,
    RESOURCES_FOR_GALACTICA,
    UNSAVORY_CONNECTIONS
}
