package xyz.zlatanov.frakkintoasters.state.card;

public enum MotiveCard {
    SUBJECTS_TO_STUDY,
    SAVOR_THEIR_DEMISE,
    NO_UNNECESSARY_FORCE,
    HARVEST_THEIR_RESOURCES,
    FIGHT_WITH_HONOR,
    A_JUSTIFIED_RESPONSE,
    A_FALSE_SENSE_OF_SECURITY,
    PRESSURE_THEIR_LEADERS,
    MAKE_AN_ALLY,
    LEARN_TO_CHERISH,
    KEEP_THEM_DOCILE,
    IMPROVE_EFFICIENCY,
    END_THE_CHASE

    //TODO MISSING ONE?
}
